### ISSUE TITLE
IsoFilter.py not found

### ISSUE THREAD

**Issue by awickert** [wang3563/ESCI5980-Project2#1]
Please include here so this can be run standalone

**Comment by wang3563** [comment]
Turns out I changed IsoFilter to Ufilter and now it does not need IsoFilter.py because I included it in Ucalculation.py

**Comment by awickert** [comment]
Suggest reopening. Tried running, and returned, "global name 'IsoFilter' is not defined"

**Comment by awickert** [comment]
Looks like an improvement.

I would ensure that there is a way to run the code non-interactively.
So either include a call to main() at the bottom of Ucalculation.py or in a
separate file.

I also tried to run it and hit the error:
"global name 'IsoFilter' is not defined"

Could you fix the code and re-send?

Andy

---
Andrew D. Wickert
Department of Earth Sciences, University of Minnesota - Twin Cities
http://www.esci.umn.edu/people/Andy-Wickert
+1 612-625-6878
(Also at SAFL, Rm. 379, 2 3rd Ave. SE, Minneapolis)
